frigate:
  frigate_url: http://192.168.1.75:5000
  mqtt_server: 192.168.1.75
  mqtt_auth: false
  mqtt_username: username
  mqtt_password: password
  mqtt_port: 1883  # Optional, default: 1883
  mqtt_use_tls: False  # Optional, default: False. Use TLS for broker connection
  mqtt_tls_insecure: False  # Optional, default: False. Don't verify broker certificate
  main_topic: frigate
  camera:
    - birdcam
  object: bird
classification:
  model: model.tflite
  threshold: 0.7
webui:
  port: 7766
  host: 0.0.0.0
